import IQuestao from '../interfaces/IQuestao';

export const questoes_meio_ambiente_cidadania: IQuestao[] = [
    {
        id: 'MAC1',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Meio Ambiente e Cidadania"
    },
    {
        id: 'MAC2',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Meio Ambiente e Cidadania"
    },
    {
        id: 'MAC3',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Meio Ambiente e Cidadania"
    },
    {
        id: 'MAC4',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Meio Ambiente e Cidadania"
    },
    {
        id: 'MAC5',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Meio Ambiente e Cidadania"
    },
    {
        id: 'MAC6',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Meio Ambiente e Cidadania"
    },
    {
        id: 'MAC7',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Meio Ambiente e Cidadania"
    },
    {
        id: 'MAC8',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Meio Ambiente e Cidadania"
    },
    {
        id: 'MAC9',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Meio Ambiente e Cidadania"
    },
    {
        id: 'MAC10',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Meio Ambiente e Cidadania",
    }
]

export const questoes_legislacao_transito: IQuestao[] = [
    {
        id: 'LT1',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Legislação de Trânsito"
    },
    {
        id: 'LT2',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Legislação de Trânsito"
    },
    {
        id: 'LT3',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Legislação de Trânsito"
    },
    {
        id: 'LT4',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Legislação de Trânsito"
    },
    {
        id: 'LT5',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Legislação de Trânsito"
    },
    {
        id: 'LT6',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Legislação de Trânsito"
    },
    {
        id: 'LT7',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Legislação de Trânsito"
    },
    {
        id: 'LT8',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Legislação de Trânsito"
    },
    {
        id: 'LT9',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Legislação de Trânsito"
    },
    {
        id: 'LT10',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Legislação de Trânsito"
    }
]

export const questoes_direcao_defensiva: IQuestao[] = [
    {
        id: 'DD1',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Direção Defensiva"
    },
    {
        id: 'DD2',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Direção Defensiva"
    },
    {
        id: 'DD3',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Direção Defensiva"
    },
    {
        id: 'DD4',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Direção Defensiva"
    },
    {
        id: 'DD5',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Direção Defensiva"
    },
    {
        id: 'DD6',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Direção Defensiva"
    },
    {
        id: 'DD7',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Direção Defensiva"
    },
    {
        id: 'DD8',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Direção Defensiva"
    },
    {
        id: 'DD9',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Direção Defensiva"
    },
    {
        id: 'DD10',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Direção Defensiva",
    }
]

export const questoes_primeiros_socorros: IQuestao[] = [
    {
        id: 'PS1',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Primeiros Socorros"
    },
    {
        id: 'PS2',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Primeiros Socorros"
    },
    {
        id: 'PS3',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Primeiros Socorros"
    },
    {
        id: 'PS4',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Primeiros Socorros"
    },
    {
        id: 'PS5',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Primeiros Socorros"
    },
    {
        id: 'PS6',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Primeiros Socorros"
    },
    {
        id: 'PS7',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Primeiros Socorros"
    },
    {
        id: 'PS8',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Primeiros Socorros"
    },
    {
        id: 'PS9',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Primeiros Socorros"
    },
    {
        id: 'PS10',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Primeiros Socorros",
    }
]

export const questoes_mecanica_basica: IQuestao[] = [
    {
        id: 'MB1',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Mecânica Básica"
    },
    {
        id: 'MB2',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Mecânica Básica"
    },
    {
        id: 'MB3',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Mecânica Básica"
    },
    {
        id: 'MB4',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Mecânica Básica"
    },
    {
        id: 'MB5',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Mecânica Básica"
    },
    {
        id: 'MB6',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Mecânica Básica"
    },
    {
        id: 'MB7',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Mecânica Básica"
    },
    {
        id: 'MB8',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Mecânica Básica"
    },
    {
        id: 'MB9',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Mecânica Básica"
    },
    {
        id: 'MB10',
        enunciado: 'Qual a importância da educação ambiental?',
        linkImagem: 'educacao_ambiental.jpg',
        alternativa1: 'Promove a conscientização sobre os problemas ambientais',
        alternativa2: 'Incentiva a adoção de práticas sustentáveis',
        alternativa3: 'Contribui para a formação de cidadãos responsáveis',
        alternativa4: 'Todas as alternativas acima',
        resposta: 'Todas as alternativas acima',
        explicacao: 'A educação ambiental é essencial para promover a conscientização sobre os problemas ambientais, incentivar a adoção de práticas sustentáveis e contribuir para a formação de cidadãos responsáveis.',
        nomeMateria: "Mecânica Básica",
    }
]